util/auto_recover.go, util/util_test.go
Add util function: WithRecoverGo,  in order to avoid sentinel interrupt main process when internal panic.
None
None
None
None
=> auto recover routine to avoid sentinel interrupt main process.

core/base/metric_item_test.go, core/log/metric/aggregator.go, core/log/metric/common.go, core/log/metric/common_test.go, core/log/metric/reader.go, core/log/metric/searcher.go, core/log/metric/writer.go, core/log/slot.go
Add Sentinel metric log implementation. For details of the format, see [the document](https://github.com/alibaba/Sentinel/wiki/Metrics#metric-log).
Resolves #5 
Add `MetricSearcher` and `MetricWriter` implementation, which are analogous to Java version. The default log directory is `~/logs/csp`.
Note: the design of the interfaces could be improved later.
- Run the test cases.
- Run the demo and see the output of the metric log.
Additional unit test cases are needed, but it's hard to test with the actual file. Suggestions are welcome!
=> Add metric log implementation

core/flow/rule_manager.go, core/flow/tc_throttling.go, core/flow/tc_throttling_test.go, util/time.go
Add throttling traffic shaping implementation based on algorithms like leaky bucket + "virtual queue".
Resolves #32 
Some considerations:
- We use a timestamp-based "virtual queue" here instead of a real queue that caches the user task.
- To make it more accurate when calculating the interval between two requests (e.g. QPS > 1000), we use nanosecond here rather than millisecond (though the queueing timeout in the flow rule definition is millisecond-based).
- The implementation is not strictly accurate in multi-threaded scenarios due to consideration for performance. We may introduce a "strict mode" in later versions.
Run the test cases.
Here is a sample rule for integration test:
```go
{
ID:                1,
Resource:          "some-test",
MetricType:        flow.QPS,
Count: …
```
=> Add throttling traffic shaping implementation

core/config/entity.go, core/config/local_storage.go, util/string.go
Add general configuration definition and mechanism for initializing conf from YAML file and system env.
Resolves #23 
The definition overview: https://github.com/sentinel-group/sentinel-golang/issues/23#issuecomment-585093059
Priority: `system env > YAML file`
Users can provide the YAML file path via the `InitConfigFromFile` function or from system env (via `InitConfig` function). If both are absent, Sentinel will try to read conf from `sentinel.yml` in the project directory. If it does not exist, Sentinel will use the conf from system env (only some fundamental items) and default value instead.
**Note**: The functions for logging are separated from the general config to avoid circular dependency. For logging configurations, see https://github.com/sentinel-group/sentinel-golang/blob/master …
=> Add general configuration definition and initialization mechanism

api/init.go, core/config/entity.go, core/config/local_storage.go, core/system/sys_stat.go, core/system/sys_stat_test.go
Add support for collecting CPU usage for SystemRule.
NONE
Calculate the CPU usage:
- u=user+nice, k=system+irq+sirq, total=u+k+idle+steal+iowait
- usage=(udiff+kdiff)/tdiff, or 0 if tdiff=0
- Unify value to [0.0, 1.0]
Run the test cases and demo.
NONE
=> Add support for collecting CPU usage for SystemRule

ext/datasource/helper.go, ext/datasource/helper_test.go
Hotfix: If the update value is nil in PropertyUpdater, sentinel should clear downstream property.
=> Hotfix: Fix bug for SystemRulesUpdater and FlowRulesUpdater

core/circuit_breaker/circuit_breaker.go, core/circuit_breaker/circuit_breaker_test.go, core/circuit_breaker/rule.go, core/circuit_breaker/rule_manager.go, core/circuit_breaker/rule_manager_test.go, core/circuit_breaker/rule_test.go, core/circuit_breaker/slot.go, go.mod, go.sum, util/uuid.go
Add circuit breaker implementation.  Including circuitBreaker、breakerRule、breakerManager.
The design could refer to [熔断降级设计](https://github.com/alibaba/sentinel-golang/wiki/%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7)
Fixes #13
=> Issue13 circuit breaker implementation

ext/datasource/datasource.go, ext/datasource/error.go, ext/datasource/etcdv3/etcdv3.go, ext/datasource/etcdv3/etcdv3_example.go, ext/datasource/file/refreshable_file.go, ext/datasource/helper.go, go.mod, go.sum
extend etcdv3 as datasource.
1.  Introduce DatasourceGenerator to generate Etcdv3DataSource.
2. All Etcdv3DataSources generated by DatasourceGenerator instance will reuse the etcdv3 client long lived http connection.
3. Etcdv3DataSource could be closed,  if all Etcdv3DataSources generated by DatasourceGenerator instance were clsoed, DatasourceGenerator will be closed, which means etcdv3 client will be closed.
4. DatasourceGenerator only expose the function Generate.
=> Etcdv3 datasource

api/api.go, core/base/context.go, core/base/slot_chain_test.go
We need to pass some data about current invocation to slots, while these data is parsed before `Sentinel.Entry()`. `EntryOptions` is a suitable place but extra attribute is required.
None.
Add a map `data map[string]interface{}` (and several functions associated) to `EntryOptions`.
=> make EntryOptions support storing custom data before Sentinel.Entry()

core/flow/rule_manager.go
Update the `buildFlowMap` execution order.
=> Update the `buildFlowMap` function execution order.

api/api.go, core/base/result.go, core/base/result_test.go, core/base/slot_chain.go, core/circuit_breaker/slot.go, core/flow/slot.go, go.mod, go.sum
I want to modify the original code as little as possible, but now it exists a lot of temporary token result, so my modify will look very ugly, as shown below。
#137
=> Add result token pool  (#137)

core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/circuit_breaker_test.go, core/circuitbreaker/rule.go, core/circuitbreaker/rule_manager.go, core/circuitbreaker/stat_slot.go, example/circuitbreaker/circuit_breaker_example.go
Polish code of circuit breaker module.
NONE
Improve comments, naming and logging of circuit breaker module.
Run the test cases and demo.
NONE
=> Polish code of circuit breaker module

adapter/dubbo/consumer_filter.go, adapter/dubbo/provider_filter.go, adapter/grpc/client.go, adapter/grpc/server.go, api/tracer.go, api/tracer_test.go
Polish `api.Tracer` with new error tracing mechanism (set error to entry and record on request completed).
Related to #143
=> Polish api.Tracer with new error tracing mechanism

tests/entry_benchmark_concurrency_test.go, tests/entry_benchmark_test.go, tests/memory_test.go
=> Add benchmark

api/api.go, api/init.go, core/base/context.go, core/base/slot_chain.go, core/config/config.go, core/config/entity.go, util/time.go, util/time_test.go, util/time_ticker.go, util/util_test.go
1. pool EntryOption
2. optimize EntryContext pool
3. optimize time.Now
=> Optimize performance.

api/api.go, api/slot_chain.go, core/base/result.go, core/config/config.go, core/freq_params_traffic/cache/concurrent_cache.go, core/freq_params_traffic/cache/concurrent_lru.go, core/freq_params_traffic/cache/concurrent_lru_benchmark_test.go, core/freq_params_traffic/cache/concurrent_lru_test.go, core/freq_params_traffic/cache/lru.go, core/freq_params_traffic/concurrency_stat_slot.go, core/freq_params_traffic/params_metric.go, core/freq_params_traffic/rule.go, core/freq_params_traffic/rule_manager.go, core/freq_params_traffic/rule_manager_test.go, core/freq_params_traffic/rule_test.go, core/freq_params_traffic/slot.go, core/freq_params_traffic/slot_test.go, core/freq_params_traffic/traffic_shaping.go, core/freq_params_traffic/traffic_shaping_test.go, core/stat/base/leap_array.go, example/freq_params_traffic/hot-pramas-sentinel.yml, example/freq_params_traffic/hot_params_flow_example.go, logging/logging.go, logging/logging_test.go, util/atomic.go
Frequency parameters traffic control implementation.
Supporting reject directly strategy and throttling strategy.
Using token counter to record statistics。
=> frequency parameters traffic control

api/init.go, core/config/config.go, core/config/config_test.go, core/config/entity.go, core/log/metric/aggregator.go
The wiki: [https://github.com/alibaba/sentinel-golang/wiki/通用配置项](https://github.com/alibaba/sentinel-golang/wiki/通用配置项)
had been updated.
=> Refactor config initialization

core/stat/base/leap_array_test.go
The size of BucketWrap is 24 bytes and the test for bucket wrapper size has wrong error message. 
NONE
NONE
=> fix error message of test for bucket wrapper size

core/circuitbreaker/rule_manager.go, core/flow/rule_manager.go, core/hotspot/rule_manager.go, core/hotspot/rule_manager_test.go, core/system/rule_manager.go, tests/maxsize_rule_list_benchmark_test.go
=> Optimize load rules for max size rule

core/hotspot/slot.go, core/stat/base/leap_array.go
=> Hotspot Enhancement and bug fix in AtomicBucketWrapArray

api/api_test.go, core/base/block_error.go, core/base/context_test.go, core/base/result.go, core/base/slot_chain_test.go, core/circuitbreaker/slot.go, core/flow/rule_manager.go, core/flow/tc_default.go, core/flow/tc_throttling.go, core/hotspot/traffic_shaping.go, core/system/slot.go
Improve all rule checking slots with standard `BlockError` representation.
NONE
This PR follows a simple BlockError specification:
- The `Error()` SHOULD start with `SentinelBlockError: ${blockType}`. If block message is provided, append it to the `Error()` value. The `blockMsg` is not required.
- It's recommended to carry the triggered rule and the "snapshot" value in the `BlockError`.
This PR improves all rule checking slots with more standard `BlockError` representation.
Run the test cases.
NONE
=> Improve all rule checking slots with standard BlockError representation

ext/datasource/nacos/nacos.go, ext/datasource/nacos/nacos_test.go, go.mod, go.sum
Upgrade nacos-sdk-go v1.0.0
This version optimizes a lot of things, especially config file listening and canceling。
go test ./...
=> upgrade nacos sdk

core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/rule_manager.go, core/stat/base/atomic_window_wrap_array_test.go, core/stat/base/bucket_leap_array_test.go, core/stat/base/leap_array.go, core/stat/base/leap_array_test.go
Make the start time of AtomicBucketWrapArray align to standard time.
Fix the typo in NewLeapArray.
=> Optimize the way to initialize the start time of the AtomicBucketWrapArray

api/api.go, core/base/context.go, core/base/entry.go, core/base/entry_test.go, core/base/slot_chain.go, core/base/slot_chain_test.go, core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/rule.go, core/circuitbreaker/rule_manager.go, tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
Fix the issue: #196 
add defer to handle panic in entry.Exit func and move context recovery logic to defer
#196 
UT and integration test
tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
=> fix circuit breaker half-open state issue.

api/api_test.go, core/base/slot_chain.go, core/base/slot_chain_test.go, core/circuitbreaker/stat_slot.go, core/hotspot/concurrency_stat_slot.go, core/stat/stat_slot.go
Make StatSlot.OnCompleted sense
Ut
=> Make StatSlot.OnCompleted sense

core/flow/rule_manager.go, core/flow/tc_warm_up.go, example/warm_up/qps_warm_up_example.go
https://github.com/alibaba/sentinel-golang/blob/36a09c509daba8e3d790157f55af7587b688d39b/core/flow/tc_warm_up.go#L21
Define storedTokens as uint64 might cause bug.
https://github.com/alibaba/sentinel-golang/blob/36a09c509daba8e3d790157f55af7587b688d39b/core/flow/tc_warm_up.go#L78
=> fix bug: incorrectly defined storeToken using uint in warmup flow control

adapter/echo/middleware_test.go, adapter/gin/middleware_test.go, adapter/grpc/client_test.go, adapter/grpc/server_test.go, adapter/micro/client_test.go, adapter/micro/server_test.go, core/flow/rule.go, core/flow/rule_manager.go, core/flow/rule_manager_test.go, core/flow/slot.go, core/flow/tc_default.go, core/flow/tc_warm_up.go, core/flow/traffic_shaping.go, example/qps/qps_limit_example.go, example/qps/qps_limit_example_test.go, example/warm_up/qps_warm_up_example.go, example/warm_up/qps_warm_up_example_test.go, ext/datasource/helper.go, ext/datasource/helper_test.go, tests/testdata/extension/helper/FlowRule.json
1.  remove cluster flow control code related.
2. rename flow.FlowRule to flow.Rule
=> Refine flow module code

core/system/rule.go, core/system/rule_manager.go, core/system/rule_manager_test.go, core/system/rule_test.go, core/system/slot.go, core/system/slot_test.go, ext/datasource/consul/consul_test.go, ext/datasource/helper.go, ext/datasource/helper_test.go, ext/datasource/property_test.go
=> rename system.SystemRule to system.Rule

core/system/slot.go, core/system/slot_test.go
This attribute seems superfluous.
It doesn't seem to have been really used.
Tests and Example can pass.
=> refactoring: Delete "SlotName" in 'core/system/slot.go'.

core/flow/rule.go, core/flow/rule_manager.go, ext/datasource/helper_test.go, tests/testdata/extension/helper/FlowRule.json
Remove field LimitOrigin in flow.Rule B/C LimitOrigin is redundancy
CI passs
=> Remove field LimitOrigin in flow.Rule

adapter/echo/middleware_test.go, adapter/gin/middleware_test.go, adapter/grpc/client_test.go, adapter/grpc/server_test.go, adapter/micro/client_test.go, adapter/micro/server_test.go, core/flow/rule.go, core/flow/rule_manager.go, core/flow/rule_manager_test.go, core/flow/tc_default.go, example/qps/qps_limit_example.go, example/qps/qps_limit_example_test.go, example/warm_up/qps_warm_up_example.go, example/warm_up/qps_warm_up_example_test.go, ext/datasource/helper_test.go, tests/testdata/extension/helper/FlowRule.json
Break down flow.ControlBehavior to flow.AllocationStrategy and flow.ControlEffect
```go
const (
Default AllocationStrategy = iota
WarmUp
)
const (
Reject ControlEffect = iota
Throttling
)
```
=> Break down flow.ControlBehavior to flow.TokenCalculateStrategy and flow.ControlBehavior

.github/workflows/go.yml
Because of golangci-lint's default timeout is 1m. It might cause CI failure.
=> Fix CI accidental failure

core/circuitbreaker/rule_manager.go, core/circuitbreaker/slot.go, core/circuitbreaker/stat_slot.go, core/flow/rule_manager.go, core/hotspot/rule_manager.go, core/system/rule_manager.go, core/system/rule_manager_test.go, core/system/slot.go, ext/datasource/helper_test.go
Refine GetResRule func and GetRules func in flow/circuitbreaker/hotspot/system module
=> Refine GetResRule API and GetRules API in flow/circuitbreaker/hotspot/system module

api/init.go, core/config/config.go, core/config/entity.go, core/log/metric/writer.go, logging/logging.go
Improve sentinel initialization mechanism
1. The logging module init function sets the default logger to be a file logger(sentinel-record.log). Even if the user does not initialize sentinel, it will work properly.
2. Reset logger by configEntity/yaml/default is optional. Reset logger only if the user sets logger in configuration.
None
UT
@sczyh30
=> Improve Config API

api/slot_chain.go, core/base/result.go, core/isolation/doc.go, core/isolation/rule.go, core/isolation/rule_manager.go, core/isolation/rule_manager_test.go, core/isolation/slot.go, example/isolation/concurrency_limitation_example.go
split isolation pkg to implement concurrency traffic control
=> split isolation pkg to implement concurrency traffic control

adapter/echo/middleware_test.go, adapter/gin/middleware_test.go, api/slot_chain.go, core/base/stat.go, core/base/stat_test.go, core/config/config.go, core/config/entity.go, core/flow/rule.go, core/flow/rule_manager.go, core/flow/rule_manager_test.go, core/flow/slot.go, core/flow/slot_test.go, core/flow/standalone_stat_slot.go, core/flow/tc_default.go, core/flow/tc_throttling.go, core/flow/tc_throttling_test.go, core/flow/tc_warm_up.go, core/flow/traffic_shaping.go, core/stat/base/sliding_window_metric.go, core/stat/base/sliding_window_metric_test.go, core/stat/base_node.go, core/stat/resource_node.go, core/stat/stat_slot.go, tests/testdata/extension/helper/FlowRule.json
Support arbitrary statistic interval for normal flow rule
stat parameters configurable
Resolve 
#129 
#167 
Support arbitrary statistic interval for normal flow rule
1. If user doesn't set StatisticConfig, that means using default metric statistic.
2.If user specifies StatisticConfig and meets the compliance of CheckValidityForReuseStatistic,
will build readonly metric statistic based on resource's global statistic.
3.If user specifies StatisticConfig and doesn't meet the compliance of CheckValidityForReuseStatistic,
will generate independent token bucket statistic for this rule.
TODO
1. unit test
2. integration test
=> Support arbitrary statistic interval for flow control && stat parameters configurable

core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/circuit_breaker_test.go, core/circuitbreaker/rule_manager.go
=> Imp: cb state

logging/logging.go, logging/logging_test.go
Use string builder grow to reduce memory allocations in logging pkg.
Benchmark result:
```
goos: darwin
goarch: amd64
pkg: github.com/alibaba/sentinel-golang/logging
BenchmarkAssembleMsg/assemble_msg_using_string_builder_with_grow-4                742695              1681 ns/op             624 B/op          8 allocs/op
BenchmarkAssembleMsg/assemble_msg_using_string_builder_without_grow-4             678778              1901 ns/op             728 B/op         12 allocs/op
```
=> Refine string builder usage in logging pkg

core/base/stat.go, core/base/stat_test.go, core/isolation/slot.go, core/stat/base_node.go, core/stat/stat_slot.go, core/system/slot.go, core/system/slot_test.go, example/hotspot_param_flow/concurrency/hotspot_params_concurrency_example.go
=> Abstract concurrency-related operations as ConcurrencyStat interface and polish StatNode

api/init.go, core/config/config.go, core/config/config_test.go
1. Refine config logic
2. Add `func InitWithParser(configBytes []byte, parser func([]byte) (*config.Entity, error)) (err error) ` to initialize Sentinel
=> Enhance config API, support initialization by config parser

core/stat/base/atomic_window_wrap_array_test.go, core/stat/base/bucket_leap_array.go, core/stat/base/leap_array.go, core/stat/base/metric_bucket.go
A panic operation will cause the program to exit
fixes:https://github.com/alibaba/sentinel-golang/issues/278
go test ./...
=> purge existing panic operations

core/flow/rule_manager.go, core/flow/rule_manager_test.go, core/flow/tc_throttling.go, core/flow/tc_throttling_test.go
Fix bug that StatIntervalInMs do not take effect in throttling checker.
As the doc [流量控制](https://github.com/alibaba/sentinel-golang/wiki/%E6%B5%81%E9%87%8F%E6%8E%A7%E5%88%B6) describes:
> 这里特别强调一下StatIntervalInMs和Threshold这两个字段，这两个字段决定了流量控制器的灵敏度。以 Direct + Reject 的流控策略为例，流量控制器的行为就是在StatIntervalInMs周期内，允许的最大请求数量是Threshold。比如，如果StatIntervalInMs是10000，Threshold是10000，那么流量控制器的行为就是10s内运行最多10000次访问。
By unit test and example.
=> Fix bug that StatIntervalInMs do not take effect in throttling checker

api/api.go, core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/rule_manager.go, core/flow/rule_manager.go, core/hotspot/cache/lru.go, core/hotspot/rule_manager.go, core/isolation/rule_manager.go, core/log/metric/aggregator.go, core/log/metric/common.go, core/log/metric/reader.go, core/stat/base/leap_array.go, core/stat/base/sliding_window_metric.go, core/system/rule_manager.go, ext/datasource/helper.go, ext/datasource/hotspot_rule_converter.go
Make map&slice with init capacity to decrease grow cost.
I have done a simple benchmark of map.  
Benchmark code:
```go
func BenchmarkMap(b *testing.B) {
for len := 16; len <= 2048; len *= 2 {
nohint := fmt.Sprintf("map-len-%d-nohint", len)
b.Run(nohint, func(b *testing.B) {
keys := stringutil.RandomStrings(10, len)
for i := 0; i < b.N; i++ {
m := make(map[string]struct{})
for _, k := range keys {
m[k] = struct{}{}
}
}
})
hint := fmt.Sprintf("map-len-%d-hint", len)
b.Run(hint, func(b *testing.B) {
keys := stringutil.RandomStrings(10, len)
for i := 0; i < b.N; i++ {
m := make(map[string]struct{}, len)
for _, k := range keys {
m[k] = struct{}{}
}
}
})
}
}
```
Benchmark result:
```
goos: darwin
goarch: amd64
pkg: test
BenchmarkMap/map-len-16-nohint-4                 1024162              1207 …
```
=> Make map&slice with init capacity to decrease grow cost

core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/rule_manager.go
when slowRequestRatio was set to 1.0d, requests will **never** be blocked. Because the currentRatio will never be bigger than 100%
Special treatment for case when slowRequestRatio was set to 1.0d
=> fix bug in circuit_breaker.go about SlowRequestRatio

core/flow/rule_manager.go, core/flow/rule_manager_test.go, ext/datasource/helper.go
In order to avoid the meaningless updates to the property, downstream of property manager should
cache last update value to check consistency.
Fix:#111
Using reflect.deepequal,maybe we need to think about performance
ut
=> Flow rule cache/check

core/hotspot/rule_manager.go, core/hotspot/rule_manager_test.go, ext/datasource/helper.go
In order to avoid the meaningless updates to the property, downstream of property manager should
cache last update value to check consistency.
Fix:#111
Using reflect.deepequal,maybe we need to think about performance
ut
=> Loading hotspot rule supports cache

core/circuitbreaker/rule_manager.go, core/circuitbreaker/rule_manager_test.go, ext/datasource/helper.go
In order to avoid the meaningless updates to the property, downstream of property manager should
cache last update value to check consistency.
Fix:#111
Using reflect.deepequal,maybe we need to think about performance
ut
=> Loading circuitbreaker rule supports cache

core/hotspot/rule_manager.go, core/isolation/rule_manager.go, core/isolation/rule_manager_test.go
In order to avoid the meaningless updates to the property, downstream of property manager should
cache last update value to check consistency.
Fix:#111
Using reflect.deepequal,maybe we need to think about performance
ut
=> Loading isolation rule supports cache

tests/benchmark/isolation/isolation_slot_benchmark_test.go
Add isolation slot benchmark.
Below is a benchmark result on my local machine.
```
goos: darwin
goarch: amd64
pkg: github.com/alibaba/sentinel-golang/tests/benchmark/isolation
Benchmark_IsolationSlotCheck_Loop-4              1292761               909 ns/op             120 B/op          4 allocs/op
Benchmark_IsolationSlotCheck_Concurrency4-4      2840018               442 ns/op             120 B/op          4 allocs/op
Benchmark_IsolationSlotCheck_Concurrency8-4      2446152               599 ns/op             120 B/op          4 allocs/op
Benchmark_IsolationSlotCheck_Concurrency16-4     2040709               696 ns/op             120 B/op          4 allocs/op
Benchmark_IsolationSlotCheck_Concurrency32-4     2602790               448 ns/op             120 B/op          4 allocs/op
```
=> Add isolation slot benchmark

tests/benchmark/flow/flow_benchmark_test.go
enhance flow benchmark test
增加了flow 的benchmark test, 测试flow.slot.Check()
run tests/core/flow/flow_benchmark_test.go
以下测试均在windows 64， 8c环境下进行
```
load flow.Rule{
Resource:               "abc",
TokenCalculateStrategy: flow.Direct,
ControlBehavior:        flow.Reject,
Threshold:              10,
StatIntervalInMs:       1000,
RelationStrategy:       flow.CurrentResource,}
goos: windows
goarch: amd64
Benchmark_DirectReject_SlotCheck_4-8     6016041               231 ns/op               160 B/op          1 allocs/op
Benchmark_DirectReject_SlotCheck_8-8     6468952               214 ns/op               160 B/op          1 allocs/op
```
```
load flow.Rule{
Resource:               "abc",
TokenCalculateStrategy: flow.WarmUp,
ControlBehavior:        flow.Reject,
Threshold:              100, …
```
=> Add flow benchmark test

tests/benchmark/circuitbreaker/circuitbreaker_benchmark_test.go
add circuitbreaker benchmark test
增加了circuitbreaker的benchmark test, 测试circuitbreaker.slot.Check()
run tests/core/circuitbreaker/circuitbreaker_benchmark_test.go
以下测试均在windows 64， 8c环境下进行
```
load circuitbreaker.Rule{
Resource:         "abc",
Strategy:         circuitbreaker.SlowRequestRatio,
RetryTimeoutMs:   1000,
MinRequestAmount: 5,
StatIntervalMs:   1000,
MaxAllowedRtMs:   20,
Threshold:        0.1,}
goos: windowsp
goarch: amd64
Benchmark_SlowRequestRatio_SlotCheck_4-8     11569263               92.2 ns/op               16 B/op          1 allocs/op
Benchmark_SlowRequestRatio_SlotCheck_8-8     12800313               109 ns/op                16 B/op          1 allocs/op
```
```
load circuitbreaker.Rule{
Resource:         "abc",
Strategy:         circuitbreaker.ErrorRatio, …
```
=> Add circuitbreaker benchmark test

core/circuitbreaker/circuit_breaker.go, core/stat/base/leap_array.go
```
Benchmark_SlowRequestRatio_SlotCheck_4-32     	{"timestamp":"2020-11-21 07:11:18.18210","caller":"circuit_breaker.go:345","logLevel":"ERROR","msg":"Failed to get current bucket in slowRequestLeapArray.currentCounter()"}
Provided time timeMillis=1605942677000 is already behind old.BucketStart=1605942678000. now=1605942677999
github.com/alibaba/sentinel-golang/core/stat/base.(*LeapArray).currentBucketOfTime
/home/ytlou/share/golang/sentinel-golang/core/stat/base/leap_array.go:204
github.com/alibaba/sentinel-golang/core/stat/base.(*LeapArray).CurrentBucket
/home/ytlou/share/golang/sentinel-golang/core/stat/base/leap_array.go:164
github.com/alibaba/sentinel-golang/core/circuitbreaker.(*slowRequestLeapArray).currentCounter
/home/ytlou/share/golang/sentinel-golang/core/circuitbreaker/circuit …
```
=> Fix bug when leap array as token bucket(sample bucket is 1)

core/base/result.go, core/flow/slot.go, core/flow/tc_throttling.go, core/flow/tc_throttling_test.go, core/hotspot/slot.go, core/hotspot/traffic_shaping.go
Fix bugs of throttling control behavior in flow control module, including overflow bug and time unit bug of wait duration.
Fixes #331 
- Change semantic of `waitMs` to `nanosToWait` in `TokenResult` and polish related stat slots. Here we SHOULD use nanos instead of millis, or the queueing interval may not be accurate.
- Fix the bug that unsigned `estimatedQueueingDuration` in throttling checker may overflow. Use int64 instead.
Run the test cases and demo.
NONE.
=> Fix bugs of throttling control behavior in flow control module

core/stat/base/leap_array.go, core/stat/base/leap_array_test.go
first param of function ` NewLeapArray`   can  not  be  zero.  Or  it  will  cause panic  `runtime error: divide by zero`
=> Add sampleCount zero checking in NewLeapArray func

core/stat/base/leap_array.go
On 32-bit os, pointers occupy 4 bytes, currently 8 bytes by default, resulting in some empty buckets
=> atomicBucketWrapArray supports 32-bit os

core/circuitbreaker/circuit_breaker.go, core/circuitbreaker/circuit_breaker_test.go, core/circuitbreaker/rule.go
circuit breaker support probes num
fix:#411
Provides the probe count configuration to match the probe count when the circuit breaker is half-open
=> circuit breaker supported probe number

core/base/metric_item.go, core/base/stat.go, core/stat/base/metric_bucket_test.go, core/stat/base/sliding_window_metric.go
Add a new independent metric for timeout, it records how many requests was failed due to timeout, this data is useful to improve the precision of concurrency amount statistics when a large number of requests timeout
=> feat: add timeout counter metric

core/flow/slot.go, exporter/metric/empty_exporter.go, exporter/metric/exporter.go
In addition to monitoring resource passage and blocking, I think I need a metric exporter to show the status of my resource queued requests
1  add a metric to monitor queued requests 
2   add empty metric exporter because if we don’t configure metric http address, we don’t need to instantiate promethues exporter
@gorexlv
=> add a metric to monitor queued requests 

core/base/metric_item.go, core/base/stat.go, core/stat/base/metric_bucket_test.go, core/stat/base/sliding_window_metric.go
原来的MetricEvent中包含了MetricEventError用于记录错误，我们之前也一直用这个Metric记录所有的错误，但现在业务希望将一些自定义错误和RPC调用错误区别开，例如RPC请求成功了但是返回了特定的响应值或者RT超过特定阈值定义为业务错误，而RPC调用失败/超时等定义为RPC错误。
=> feat:  add biz-defined error counter

.github/workflows/go.yml, .golangci.yml, go.mod, go.sum
Refactor CI workflow and split CI into two parts with golangci-lint-action.
Update go version to 1.16 in `go.mod`.
Resloves #499 
The CI should pass.
NONE
=> Refactor CI workflow

.github/workflows/go.yml
update args of golangci-lint in ci.yml according to official guides
according to comment of https://github.com/golangci/golangci-lint-action/issues/618#issuecomment-1587781568
relation pr https://github.com/golangci/golangci-lint-action/pull/769
=> update args of golangci-lint in ci.yml

core/log/metric/common.go, core/log/metric/writer.go, core/log/metric/writer_test.go, util/file.go, util/file_test.go
impove sentinel latest metric log file name to xxx-metrics.log. 
Fix the latest file name format for convenient log collection.
NONE
1. replace func `nextFileNameOfTime`  with func `rotateWithDateAndNewFileName` 
2. init `latestOpSec` before roll log file when app starting
The implementation can be verified via go test.
=> Upgrade the latest Metric log file name to a fixed format

core/circuitbreaker/rule.go, core/circuitbreaker/rule_test.go, core/hotspot/rule.go
bug-fix
Fixes 
- https://github.com/alibaba/sentinel-golang/issues/563
- typo
add more fields for compare
add one  more test case
=> [bug-fix] probeNum参数更新，loadRule生效

core/hotspot/traffic_shaping.go
Fix batch count exceeding threshold issue caused by first time access or expired lastPassTime in queuing strategy
Fixes: #593 
* Special treatment for first visit
* LastTime of visits exceeding 1 second will be returned to 1 second ago
You can verify that the problem has been fixed by running the sample in the issue
=> fix: Fix batch count exceeding threshold issue caused by first time access or expired lastPassTime in queuing strategy

core/flow/rule.go, core/flow/rule_manager.go, core/flow/rule_manager_test.go, core/flow/slot_test.go, core/isolation/rule.go, core/isolation/rule_manager.go, core/isolation/slot_test.go, ext/datasource/helper_test.go
By allowing resource names to be defined using regex patterns, users can apply unified rules to groups of resources that match specific naming conventions or dynamic patterns (e.g., RESTful API endpoints with variable path parameters). This enhancement reduces the need for repetitive rule definitions and improves adaptability to evolving service structures
1. Added a Regex boolean flag to FlowRule and IsolationRule to mark whether the Resource uses a regular expression.
2. Rules with regex patterns are stored in a dedicated regexRulesMap to separate them from static resource rules.
3. Find regex-based rules using pattern matching when getRulesOfResource.
4. Improved performance by caching compiled regex patterns to prevent redundant compilations during repeated evaluations.
1. Define a …
=> [feature] support regex in flow control and isolation for resource name
