.gitignore
core/base/global_variable.go
core/base/result.go
core/base/slot_chain.go
core/base/slot_chain_test.go
core/base/stat.go
core/base/stat_test.go
core/datasource/property.go
core/stat/base/atomic_window_wrap_array_test.go
core/stat/base/bucket_leap_array.go
core/stat/base/bucket_leap_array_test.go
core/stat/base/leap_array.go
core/stat/base/leap_array_test.go
core/stat/base/metric_bucket.go
core/stat/base/metric_bucket_test.go
core/stat/base/slidingwindow_metric.go
core/stat/base/slidingwindow_metric_test.go
core/stat/base/triablemutex.go
core/stat/base/triablemutex_test.go
core/stat/base_node.go
core/stat/node_storage.go
core/stat/resource_node.go
core/stat/slot.go
go.mod
logging/logging.go
logging/logging_test.go
util/safe.go

statistic data structure based on sliding window
Fixes #8

Issue8 statistic slot and statistic data structure

---

.gitignore
api/api.go
api/api_test.go
api/option.go

Use builder-pattern-liked API to improve flexibility of api.Entry (SphU.entry)

---

core/stat/base/atomic_window_wrap_array_test.go
core/stat/base/bucket_leap_array.go
core/stat/base/bucket_leap_array_test.go
core/stat/base/leap_array.go
core/stat/base/leap_array_test.go
core/stat/base/metric_bucket.go
core/stat/base/slidingwindow_metric.go
core/stat/base_node.go

Issue22 change windowWrap.value from interface{} to atomic.Value

---

core/flow/rule.go
core/flow/rule_manager.go
core/flow/slot.go
core/flow/tc_default.go
core/flow/tc_throttling.go
core/flow/traffic_shaping.go

Add basic flow control features, including flow rule management and traffic shaping controller mechanism.
Resolves #12 
Run the test cases and demo.
Something to be improved later:
- Minimize the operations when rules are updated, especially for those with advanced control behavior (of which the traffic shaping controller is **stateful**). If the relevant factor value is not modified, we could keep the old traffic shaping controller rather than reconstruct a new one.

Add basic flow control module

---

core/base/stat.go
core/stat/base/atomic_window_wrap_array_test.go
core/stat/base/bucket_leap_array.go
core/stat/base/bucket_leap_array_test.go
core/stat/base/leap_array.go
core/stat/base/leap_array_test.go
core/stat/base/sliding_window_metric.go
core/stat/base/sliding_window_metric_test.go
core/stat/base_node.go
core/stat/resource_node.go
core/stat/resource_node_test.go

Add sampleCount/interval->SlidingWindowMetric map to ResourceNode.
polish stat pkg, rename windowWrap to bucketWrap

Refactor stat node and polish stat pkg

---

.gitignore
core/log/metric/aggregator.go
core/log/metric/aggregator_test.go
core/log/metric/common.go
core/log/metric/common_test.go
coverage.sh

contain file: aggregator.go, common.go

Add unit test for metric log

---

.travis.yml

support go 1.14 in CI
Fixes #66

support go 1.14 in CI

---

README.md
util/file_test.go
util/string_test.go
util/time.go
util/time_test.go

Add unit test for util package
Fixes #48

Add unit test for common util

---

core/system/rule_manager.go
core/system/rule_manager_test.go
core/system/rule_test.go
core/system/slot_test.go
core/system/sys_stat.go
core/system/sys_stat_test.go

Signed-off-by: xu wu <wuxu1103@163.com>
Add unit test for core/system directory.
Fixes #47 
When I run command "go test -v -coverprofile=cover.out" in this directory, the output is as follows：
PASS
coverage: 77.1% of statements
ok  	github.com/alibaba/sentinel-golang/core/system	0.009s

add unit test for core/system

---

util/atomic.go
util/atomic_test.go

Add atomic bool in util

---

api/init.go
core/config/config.go
core/config/config_test.go
core/config/constant.go
core/config/entity.go
core/log/metric/aggregator.go
core/log/metric/writer.go
util/file.go

Polish code and comment of config and init package.
NONE
- Improve logs and fix tiny problems of config and metric log pkg
- Improve init functions
- Polish comments of config, metric log and init package
Run the test cases
NONE

Polish code and comment of config and init package

---

ext/datasource/datasource.go
ext/datasource/property.go
ext/datasource/property_test.go

Enhance datasource framework.

---

core/flow/rule_manager.go
core/system/rule_manager.go
ext/datasource/helper.go
ext/datasource/helper_test.go
tests/testdata/extension/plugin/FlowRule.json
tests/testdata/extension/plugin/SystemRule.json

Encapsulate converter(default json) and updater related logic for specific property.
properties:
1. []system.SystemRule
2. []flow.FlowRule

Add helper for system.SystemRule and flow.FlowRule in datasource

---

api/tracer.go
api/tracer_test.go

Polish error `Tracer` in `api` pkg.
NONE
- Add `TraceError` function to record the error to the statistic structure of the target resource.
- Polish comments in `tracer.go`
Run the demo and try to trace error when passed.
The test cases of `TraceError` was not provided as it's hard to mock a package-level function (GetResourceNode).

Polish error Tracer

---

core/system/rule_manager.go
core/system/rule_manager_test.go

Remove the channel ruleChan which seems to have no obvious meaning.
LoadRules() call onRuleUpdate() to load system rules.
Add ClearRules() to clear all the previous rules.
Signed-off-by: xu wu <wuxu1103@163.com>
The implementation of LoadRules() in rule_manager.go might be not elegant, and the channel ruleChan seems to have no obvious meaning.
Fixes 71
Remove the channel ruleChan which seems to have no obvious meaning.
LoadRules() call onRuleUpdate() to load system rules.
Add ClearRules() to clear all the previous rules.
go test runs ok.
logRuleUpdate() seems to have no obvious meaning, therefore I delete it and add some logs in its caller.

polish the method LoadRules() in system rule manager.go (#71)

---

adapter/dubbo/consumer_filter.go
adapter/dubbo/consumer_filter_test.go
adapter/dubbo/fallback.go
adapter/dubbo/provider_filter.go
adapter/dubbo/provider_filter_test.go
adapter/dubbo/util.go
adapter/dubbo/util_test.go

Fix bugs and polish code in dubbo-go adapter.
NONE
- Add `TraceError` operation when `onResponse` result has error.
- Fix the bug that may cause entry complete-leak (not exited) when the interface entry passes but the method entry is blocked.
- Reformat the code.
Run the dubbo-go demo with Sentinel filter (the test cases need improving).

Fix bugs and polish code in dubbo-go adapter

---

ext/datasource/file/refreshable_file.go
ext/datasource/file/refreshable_file_test.go
go.mod

Refine file datasource code and add ut

Refine file datasource code and add ut

---

adapter/grpc/client.go
adapter/grpc/client_test.go
adapter/grpc/options.go
adapter/grpc/server.go
adapter/grpc/server_test.go

Polish gRPC-go adapter.
NONE
- Refactor function name of creating interceptors and polish related comments.
- Add `TraceError` operation when the result has errors.
- Improve test cases.
Run the test cases.
NONE

Polish gRPC-go adapter

---

adapter/dubbo/consumer_filter_test.go
adapter/dubbo/provider_filter_test.go
adapter/dubbo/util_test.go
core/flow/rule_manager.go
core/log/metric/aggregator.go
core/log/metric/aggregator_test.go
core/log/metric/reader.go
core/stat/node_storage.go
core/system/rule_manager.go
core/system/rule_manager_test.go

Polish codes in some details, for example
* remove unreachable code
* init a map elegantly, [blog.golang.org/maps](https://blog.golang.org/maps)

Polish code in some details

---

.travis.yml

Signed-off-by: wuxu <wuxu1103@163.com>
PR#139 added  goimports tool to detect imports are organized in groups or not. However, goimports is not the basic tool of golang, we have to install it manually.
Fixes #135
I'm very sorry for this bug, and I have test it today.

Install goimports for CI

---

core/config/config.go
core/log/metric/aggregator.go

add UpdateMetricLogFlushIntervalSec function to allow update metric log flush interval in runtime as a degrade manner

feat: allow to disable metric log flush in runtime

---

core/stat/base/bucket_leap_array_test.go

Fix bug in unit test Test_UpdateBucket_Concurrent

---

api/slot_chain.go
core/circuitbreaker/circuit_breaker.go
core/circuitbreaker/rule.go
core/circuitbreaker/rule_manager_test.go
core/circuitbreaker/slot.go
core/circuitbreaker/stat_slot.go
example/circuitbreaker/circuit_breaker_example.go
ext/datasource/helper.go
ext/datasource/helper_test.go

Refine the way to instance circuit breaker rule.
1. Using unified function `circuitbreaker.NewRule` to instance circuit rule instead of three function:
`circuitbreaker.NewSlowRtRule、circuitbreaker.NewErrorRatioRule、circuitbreaker.NewErrorCountRule`
2. Using options to set rule‘s field and Provide default field value for circuit breaker rule.
Circuit breaker wiki had been updated, please review.
[https://github.com/alibaba/sentinel-golang/wiki/熔断降级](https://github.com/alibaba/sentinel-golang/wiki/熔断降级)

Polish the circuit breaker code.

---

api/slot_chain.go
core/base/block_error.go
core/hotspot/rule.go
core/hotspot/rule_manager.go
core/hotspot/slot.go
core/hotspot/traffic_shaping.go
example/hotspot_param_flow/hotspot_param_flow_example.go

Polish comments and logs in hotspot module

---

ext/datasource/consul/consul.go
ext/datasource/consul/consul_example_test.go
ext/datasource/consul/consul_test.go
ext/datasource/consul/option.go
ext/datasource/helper.go

1. refactor consul datasource
2. add example for datasource: etcdv3, consul

Refactor consul datasource and polish related code

---

ext/datasource/nacos/nacos.go

Inverted wrong nacos datasource configuration

fix nacos datasource config

---

adapter/dubbo/consumer_filter.go
adapter/dubbo/provider_filter.go

Carry invocation arguments in filters of Dubbo adapter.
Related to #181

Carry invocation arguments in filters of Dubbo adapter

---

core/log/metric/common_test.go
ext/datasource/file/refreshable_file_test.go

Resolve problems in windos unit tests
#194 
go test -race ./...

[194] fix windos run test

---

tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
tests/maxsize_rule_list_benchmark_test.go

refine circuit breaker ut to avoid massive log
UT

refine circuit breaker ut to avoid massive log

---

.github/workflows/go.yml
README.md

- Add triggering CI. when branch merging.
- Add CI badge to readme

docs & ci: Update CI configuration and Add badge.

---

api/api.go
api/doc.go
core/circuitbreaker/doc.go
core/flow/doc.go

API/flow/Circuit breaker doc.go

---

core/flow/rule.go
core/flow/rule_manager_test.go
core/system/rule.go
ext/datasource/helper_test.go

Unify the type of rule.id as string

---

adapter/echo/middleware_test.go
adapter/gin/middleware_test.go
adapter/grpc/client_test.go
adapter/grpc/server_test.go
adapter/micro/client_test.go
adapter/micro/server_test.go
api/doc.go
core/circuitbreaker/rule_manager.go
core/flow/doc.go
core/flow/rule.go
core/flow/rule_manager.go
core/flow/rule_manager_test.go
core/flow/slot.go
core/flow/tc_default.go
core/flow/tc_warm_up.go
core/hotspot/rule_manager.go
core/isolation/rule_manager.go
example/qps/qps_limit_example.go
example/qps/qps_limit_example_test.go
example/warm_up/qps_warm_up_example.go
example/warm_up/qps_warm_up_example_test.go
ext/datasource/helper_test.go
logging/logging.go
tests/testdata/extension/helper/FlowRule.json

Remove concurrency control in flow module

Remove concurrency control in flow module

---

ext/datasource/consul/consul_test.go
ext/datasource/file/refreshable_file.go
ext/datasource/file/refreshable_file_test.go
ext/datasource/nacos/nacos_test.go
tests/testdata/extension/SystemRule.json
tests/testdata/extension/SystemRule2.json
tests/testdata/extension/SystemRule3.json

enhance refreshable_file: watch source file event after remove/rename

---

core/stat/base/leap_array.go

Update comment of LeapArray.Values()

Update comment of LeapArray.Values()

---

core/stat/base/leap_array_test.go

Fix error message of unit test for bucket wrapper size.

Fix error message of unit test for bucket wrapper size

---

core/config/config.go
core/log/metric/writer.go
logging/logging.go
util/file.go

Use path/filepath pkg to do file path related operations.  Package filepath implements utility routines for manipulating filename paths in a way compatible with the target operating system-defined file paths. The filepath package uses either forward slashes or backslashes, depending on the operating system.

Use path/filepath pkg to do file path related operations

---

api/api.go
api/api_test.go
core/base/context.go
core/base/slot_chain.go
core/base/slot_chain_test.go
core/flow/slot.go
core/flow/slot_test.go
core/flow/standalone_stat_slot.go
core/flow/tc_default.go
core/flow/tc_throttling.go
core/flow/traffic_shaping.go
core/hotspot/slot.go
core/hotspot/slot_test.go
core/hotspot/traffic_shaping.go
core/isolation/slot.go
core/stat/stat_slot.go
example/isolation/concurrency_limitation_example.go

change the acquire count which I do not understand to batch count

Mod: acquire -> batch

---

ext/datasource/consul/consul.go
ext/datasource/consul/consul_example_test.go
ext/datasource/etcdv3/etcdv3.go
ext/datasource/etcdv3/etcdv3_example.go
ext/datasource/helper.go

- Some renaming
- Refactor error handling

Refine naming for ext/datasource module 

---

ext/datasource/datasource.go
ext/datasource/datasource_test.go
ext/datasource/helper_test.go

add datasource base Handle() ut
go test ./...

enhance datasource ut

---

core/stat/base/bucket_leap_array_test.go
core/stat/base/leap_array_test.go
core/stat/base/metric_bucket_test.go
core/stat/base/sliding_window_metric.go
core/stat/base/sliding_window_metric_test.go

enhance core stat ut
go test ./...

enhance core stat ut

---

core/hotspot/concurrency_stat_slot.go
util/atomic.go
util/atomic_test.go

Refactor atomic operations by using internal implementation.

Refactor atomic operations by using internal implementation

---

README.md

Promote community communication groups.
show dingding qr code

add dingding group qr code

---

api/api.go
api/slot_chain.go
core/base/slot_chain.go
core/base/slot_chain_test.go
core/circuitbreaker/rule_manager.go
core/flow/rule_manager.go
core/hotspot/rule_manager.go
core/isolation/rule_manager.go
core/misc/resource_slot_chain.go
core/misc/resource_slot_chain_test.go
core/resourcechain/resource_slot_chain.go
core/system/rule_manager.go

Refine code logic related to resource slot chain

Refine APIs of per-resource slot chain and improve rule slot registering logic in rule managers

---

core/circuitbreaker/rule_manager.go
core/isolation/rule_manager_test.go
example/isolation/concurrency_limitation_example.go
logging/logging.go
logging/logging_test.go
tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
tests/maxsize_rule_list_benchmark_test.go

enhance logging api and refine comments

---

core/base/stat.go

Use internal errors pkg to create global error var. The runtime stack is useless.

Use internal errors pkg to create global error var

---

core/flow/rule.go
core/flow/rule_manager.go
core/flow/rule_manager_test.go

Allow flow rule MaxQueueingTimeMs to be 0 even when the control behavior is `Throttling`.

Allow flow rule MaxQueueingTimeMs to be 0

---

core/flow/tc_throttling.go
core/flow/tc_throttling_test.go

Fix no limit of batch count in flow throttling checker.

Fix no limit of batch count in flow throttling checker

---

api/init.go
core/system/slot.go
util/safe.go

Temporarily not supported retrieve and update windows system stat，
Determine the system type, and if it is Windows, do not count load
Run the example and observe the log

not supported retrieve and update windows system stat

---

core/hotspot/traffic_shaping.go
core/stat/base_node.go

Remove redundant type conversion.

Remove redundant type conversion.

---

core/circuitbreaker/rule_manager.go
core/flow/rule_manager.go
core/hotspot/rule_manager.go
core/log/metric/searcher.go
core/log/metric/writer.go
core/system/rule_manager.go
core/system/sys_stat.go
logging/logging.go
logging/logging_test.go

- Logging supports auto conversion of error interface.
- Refine logging param when it is an error.
- Add more tests.

Enhance logging

---

logging/logging.go
logging/logging_test.go

Refine logging. If a string is already in json format, do not marshal again.

Refine logging

---

README.md

Only modify the position of logo picture so make it more formal lol ✨

docs : update README.md

---

ext/datasource/helper.go
ext/datasource/helper_test.go
tests/testdata/extension/helper/IsolationRule.json

Add isolation rules handler
IsolationRuleJsonArrayParser provide JSON  as the default serialization for list of isolation.Rule
IsolationRulesUpdater load the newest []isolation.Rule to downstream system component.
ut

Add isolation rules handler

---

core/hotspot/concurrency_stat_slot.go
core/hotspot/rule.go
core/hotspot/rule_manager.go
core/hotspot/traffic_shaping.go
core/hotspot/traffic_shaping_test.go

Enhance hotspot ParamsMetric

---

core/circuitbreaker/slot.go
core/flow/tc_default.go
core/flow/tc_throttling.go
core/hotspot/traffic_shaping.go
core/isolation/slot.go
core/system/slot.go
core/system/slot_test.go

Enhance block error.
#282 
- MUST specify block type.
- MUST specify related rule.
- MUST specify the snapshot value if the `RuleCheckSlot` compares with a specific metric when do checking.
- SUGGEST a simply and important message to describe the block error.

Enhance snapshot for blocked entry

---

core/stat/base/sliding_window_metric_test.go

```
=== RUN   TestMetricItemFromBucket
sliding_window_metric_test.go:238: 
Error Trace:  sliding_window_metric_test.go:238
Error:        Should be true
Test:         TestMetricItemFromBucket
--- FAIL: TestMetricItemFromBucket (0.00s)
=== RUN   TestSecondMetricsOnCondition
--- PASS: TestSecondMetricsOnCondition (0.00s)
FAIL
```
go test

fix testMetricItemFromBucket func

---

go.mod
go.sum

upgrad gopsutil supports windows load
fix:https://github.com/alibaba/sentinel-golang/issues/294

upgrad gopsutil supports windows load

---

example/circuitbreaker/error_count/circuit_breaker_error_count_example.go
example/circuitbreaker/error_ratio/circuit_breaker_error_ratio_example.go
example/circuitbreaker/slow_rt_ratio/circuit_breaker_slow_rt_ratio_example.go
example/hotspot_param_flow/concurrency/hotspot_params_concurrency_example.go

Fix typos in example comments.

Fix typos in example comments

---

go.mod
go.sum

upgrade gopsutil v3.20.11
gopsutil v3.20.11:https://github.com/shirou/gopsutil/releases/tag/v3.20.11

upgrade gopsutil

---

example/flow/qps/qps_limit_example.go
go.mod
go.sum

Update rules in concurrency for flow qps example.

---

core/hotspot/rule_manager.go

Enhance load hotspot rules
1.Use `copy on update` to reduce write lock.
2.Use updateLock serialize loading rules.
Existing logic: lock.Lock() -> build new tcMap by old tcMap -> set tcMap ->lock.Unlock()
New logic: updateLock.lock() -> lock.RLock() -> build clone tcMap -> lock.RUnlock -> build new tcMap by clone tcMap -> lock.Lock() -> set tcMap -> lock.Unlock () -> updateLock.Unlock()

Rule Manager: Enhance load hotspot rules

---

core/circuitbreaker/rule_manager.go
core/flow/rule_manager.go
core/flow/rule_manager_test.go
core/isolation/rule_manager.go
core/system/rule_manager.go
core/system/rule_manager_test.go
ext/datasource/helper.go

Make flow, breaker, isolation and system LoadRule()  serialization
Fixes #248
Likes #333

Make flow, breaker, isolation and system LoadRule()  serialization

---

api/init.go
core/system/slot.go
core/system/slot_test.go
core/system_metric/sys_metric_stat.go
core/system_metric/sys_metric_stat_test.go

Isolate system metric statistic to independent pkg core/system_metric

Isolate system metric statistic to independent pkg core/system_metric

---

core/circuitbreaker/circuit_breaker.go
core/circuitbreaker/rule.go
core/circuitbreaker/rule_manager.go
core/circuitbreaker/rule_test.go
example/circuitbreaker/error_count/circuit_breaker_error_count_example.go
example/circuitbreaker/error_ratio/circuit_breaker_error_ratio_example.go
example/circuitbreaker/slow_rt_ratio/circuit_breaker_slow_rt_ratio_example.go

Support stat sliding window bucket count config of circuit breaker.
#334

Support stat sliding window bucket count config of circuit breaker

---

core/base/metric_item.go
core/base/metric_item_test.go
core/base/stat.go
core/log/metric/aggregator.go
core/stat/base/bucket_leap_array.go
core/stat/base/bucket_leap_array_test.go
core/stat/base/metric_bucket.go
core/stat/base/metric_bucket_test.go
core/stat/base/sliding_window_metric.go
core/stat/base_node.go
core/stat/base_node_test.go

sync special/metric-event branch changes to new branch

---

api/tracer_test.go
core/base/slot_chain_test.go
core/flow/slot.go
core/flow/tc_throttling_test.go
core/hotspot/slot.go
core/hotspot/traffic_shaping_test.go
core/log/metric/aggregator.go
core/log/metric/writer.go
core/stat/base/atomic_window_wrap_array_test.go
core/stat/base/mutex_test.go
core/stat/base/stat_base_benchmark_test.go
core/system_metric/sys_metric_stat.go
ext/datasource/file/refreshable_file.go
ext/datasource/file/refreshable_file_test.go
tests/core/circuitbreaker/circuitbreaker_slot_integration_test.go
tests/core/misc/flow_slot_load_rule_test.go
util/time.go
util/time_test.go

Support mock time and ticker. We can use mock time and ticker to do unit test, which can decouple from system real time.

Support mock time and ticker

---

core/hotspot/rule.go
core/hotspot/rule_manager.go
core/hotspot/rule_manager_test.go
core/hotspot/slot.go
core/hotspot/traffic_shaping.go
example/hotspot_param_flow/qps_reject/hotspot_params_qps_reject_example.go
ext/datasource/helper_test.go

Add hotspot rule mod field for meeting the needs of monitoring mode
NO

hotspot add mod:CLOSE;MONITOR;CONTROL

---

core/flow/tc_throttling.go
core/flow/tc_throttling_test.go

…e number of cores
Modify store with cas.
Fixes #117 
as commit
run unittest TestThrottlingChecker_DoCheckQueueingParallel

Bug: contention may let go of the more requests for the number of cores

---

core/flow/rule.go
core/flow/rule_manager.go
core/flow/rule_manager_test.go

Rule Manager: support resource level rule replacement in flow module

Rule Manager: support resource level rule replacement in flow module

---

core/flow/rule_manager.go
core/isolation/rule_manager.go
core/isolation/rule_manager_test.go

Rule Manager: support resource level rule replacement in isolation module

Rule Manager: support resource level rule replacement in isolation module

---

core/hotspot/rule_manager.go
core/hotspot/rule_manager_test.go

Support resource level rule replacement in hotspot module.

Support resource level rule replacement in hotspot module

---

go.mod
go.sum

upgrade gopsutil v3.20.12->v3.20.12
v3.20.12 support cpu load on windows

upgrade gopsutil v3.20.12

---

core/circuitbreaker/rule_manager.go
core/circuitbreaker/rule_manager_test.go
core/isolation/rule_manager.go

Support resource level rule replacement in circuitBreaker module.

support resource level rule replacement in circuitBreaker module

---

core/stat/base_node.go
core/stat/base_node_test.go

feat: add NewCustomizedBaseStatNode to create the BaseStatNode with specified param
We need to create the BaseStatNode of a specific size without updating global config.

feat: add NewCustomizedBaseStatNode to create the BaseStatNode with specified param

---

core/log/metric/aggregator_test.go

Add metric log testcase

---

core/base/block_error.go
core/base/block_error_test.go
core/base/result.go
core/base/result_test.go

chore: unit test & bench test
feat:
Add option func for block error to facilitate expansion, and add New and Reset methods;
Add custom registration BlockType function;
refactor:
Optimize performance of blockType String function. detail info in bench function.

feat:block_err add opts func ,add RegistryBlockType func;

---

logging/logging.go

aliyun fc customize: fit go1.8

---

core/base/metric_item.go
logging/logging.go
tests/benchmark/hotspot/hotspot_benchmark_test.go

Aliyun fc customized: fit Go 1.8

---

core/base/metric_item.go
core/config/config.go
core/hotspot/traffic_shaping.go
core/log/metric/aggregator.go
core/log/metric/common.go
core/log/metric/common_test.go
logging/logging.go
tests/benchmark/hotspot/hotspot_benchmark_test.go

Aliyun fc customized

---

pkg/datasource/nacos/go.mod
pkg/datasource/nacos/go.sum
pkg/datasource/nacos/nacos_test.go

fix:https://github.com/alibaba/sentinel-golang/issues/400

upgrade nacos-sdk-go v1.0.8

---

core/circuitbreaker/rule.go

optimize code

---

core/stat/base/leap_array.go

Signed-off-by: Long Dai <long0dai@foxmail.com>
Fix https://github.com/dapr/components-contrib/issues/1033

Fix integer overflow on 32-bit platform

---

core/config/entity.go

经过我们测试分析，发现这个TimeCache的逻辑对于绝大多数场景是没有意义的，甚至是有害的，所以建议改成默认disable
更多详细分析我会通过issue记录

feat: disable time cache to improve performance

---

core/stat/base/sliding_window_metric.go

fix: metricItemFromBuckets missing TimeoutCounter

---

core/base/block_error.go

内部实现的限流后降级动作需要通过一个更便捷的方式获取具体的资源点，以关联具体的降级动作

feat: add block resource to block error

---

core/base/metric_item.go
core/base/stat.go
core/stat/base/metric_bucket_test.go
core/stat/base/sliding_window_metric.go

feat: add degrade metric

---

core/base/block_error_test.go
core/base/rule.go
core/circuitbreaker/rule.go
core/flow/rule.go
core/hotspot/rule.go
core/hotspot/slot.go
core/isolation/rule.go
core/system/rule.go

1. support child nodes hotspot limit
2. add RuleID method to SentinelRule interface

feat: support child nodes hotspot limit

---

api/api.go
core/base/context.go

some `slices` memory space  can  be reused .  it  is  not  necessary  to  allocate  new memory  space.

reuse the space of  slice

---

core/flow/rule_manager.go

[#475] give the correct cap of tcGenFunMap when init

---

core/base/block_error_test.go
core/base/metric_item.go
core/base/mock_rule.go
core/base/rule.go
core/base/stat.go
core/circuitbreaker/rule.go
core/flow/rule.go
core/hotspot/rule.go
core/hotspot/slot.go
core/isolation/rule.go
core/stat/base/metric_bucket_test.go
core/stat/base/sliding_window_metric.go
core/stat/common.go
core/stat/common_test.go
core/system/rule.go
go.mod
go.sum

sentinel rule interface add blockType.
Because this is an attribute of the rule, it is convenient for the state slot to obtain the rule type of the current limit through the rule.
by UT

Sentinel rule add block type hotspot set first monitor node

---

tests/benchmark/hotspot/hotspot_benchmark_test.go

pkg imported more than once (ST1019)
NONE

chore: pkg imported more than once

---

core/system_metric/sys_metric_stat.go

fix: function comment typo

---

core/base/mock_rule.go
core/base/rule.go
core/circuitbreaker/rule.go
core/flow/rule.go
core/hotspot/rule.go
core/isolation/rule.go
core/system/rule.go

Added RuleName method to SentinelRule for better understanding of the intention of the rule when logging.

feat: add RuleName() method to SentinelRule

---

core/fallback/rule.go
core/fallback/rule_manager.go
core/fallback/rule_manager_test.go
core/fallback/slot.go
core/system/rule.go
core/system/slot.go
pkg/adapters/gin/fallback.go
pkg/adapters/gin/middleware.go
pkg/adapters/gin/middleware_test.go
pkg/adapters/gin/option.go
pkg/adapters/go-zero/fallback.go
pkg/adapters/go-zero/global_middleware.go
pkg/adapters/go-zero/option.go

- add fallback rule
- support fallback for gin and go-zero web
- support mock for system rule

Feat governance gray v3

---

pkg/adapters/gin/fallback.go

fix: fallback json data

---

core/flow/slot.go

fix: default flow slot

---

core/flow/rule_manager.go

chore: remove system metric deps

---

pkg/datasource/etcdv3/etcdv3.go

log optimization, "endpointd" => "endpoints"
None

fix:log optimization

---

api/api.go
core/base/slot_chain.go
core/circuitbreaker/circuit_breaker.go
core/system_metric/sys_metric_stat.go
ext/datasource/hotspot_rule_converter.go
pkg/adapters/micro/options.go
pkg/datasource/k8s/controllers/hotspotrules_controller.go
util/time.go

fix some comments
